answer 1; git version 2.34.1
answer 2; user.name=cr1stelle user.email=cg552722@ohio.edu
answer 3; A list of git commands prompts showing all their usages.
answer 4; On branch master
    Untracked files:
     (use "git add <file>..." to include in what will be committed)
        answers.md

    nothing added to commit but untracked files present (use "git add" to track)
answer 5; On branch master
    Untracked files:
      (use "git add <file>..." to include in what will be committed)
        answers.md

    nothing added to commit but untracked files present (use "git add" to track)
answer 6; git status
On branch master
Untracked files:
  (use "git add <file>..." to include in what will be committed)
        answers.md

nothing added to commit but untracked files present (use "git add" to track)
answer 7; git commit -m "Initial commit"
On branch master
Untracked files:
  (use "git add <file>..." to include in what will be committed)
        answers.md, readme.md
answer 8; commit e603527f32d95510afe09a68d898825a21b49030 (HEAD -> master)
Author: cr1stelle <cg552722@ohio.edu>
Date:   Mon Sep 11 12:44:58 2023 -0400

    Initial commit
answer 9; Enumerating objects: 3, done.
Counting objects: 100% (3/3), done.
Writing objects: 100% (3/3), 211 bytes | 211.00 KiB/s, done.
Total 3 (delta 0), reused 0 (delta 0), pack-reused 0
To https://github.com/cr1stelle/git-lab.git
 * [new branch]      main -> main
Branch 'main' set up to track remote branch 'main' from 'origin'.
answer 10; no
answer 11;  ! [rejected]        main -> main (fetch first)
error: failed to push some refs to 'https://github.com/cr1stelle/git-lab.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
answer 12; yes
answer 13; .git .gitignore README.md
